DROP TABLE IF EXISTS VENTAS;
DROP TABLE IF EXISTS PRODUCTOS;
DROP TABLE IF EXISTS PROVEEDORES;
DROP TABLE IF EXISTS CATEGORIAS;
DROP TABLE IF EXISTS CLIENTES;

CREATE TABLE CLIENTES
(
    id INTEGER AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    direccion VARCHAR(50),
    PRIMARY KEY(id)
);

CREATE TABLE CATEGORIAS(
    id INTEGER AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE PROVEEDORES (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    contacto VARCHAR(50),
    telefono VARCHAR(50),
    email VARCHAR(100)
);

CREATE TABLE PRODUCTOS
(
    id INTEGER AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    precio DOUBLE,
    categoria_id INTEGER NOT NULL,
    proveedor_id INTEGER NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE VENTAS(
    id INTEGER AUTO_INCREMENT,
    producto INTEGER,
    cliente INTEGER,
    fecha DATE,
    unidades INT(3),
    PRIMARY KEY(id)
);

