DROP TABLE IF EXISTS RESENAS_EVENTOS;
DROP TABLE IF EXISTS INSCRIPCIONES;
DROP TABLE IF EXISTS EVENTOS;
DROP TABLE IF EXISTS SOCIOS;
  

CREATE TABLE SOCIOS(
       id INTEGER AUTO_INCREMENT,
       nombre VARCHAR(50) NOT NULL,
       alta DATE,
       PRIMARY KEY(id)
);

CREATE TABLE EVENTOS(
       id INTEGER AUTO_INCREMENT,
       nombre VARCHAR(50) NOT NULL,
       fecha DATE,
       PRIMARY KEY(id)
);

CREATE TABLE INSCRIPCIONES (
       id INTEGER AUTO_INCREMENT,
       socio INTEGER  NOT NULL,
       evento INTEGER  NOT NULL,
       PRIMARY KEY(id)
);
           

CREATE TABLE RESENAS_EVENTOS (
    id INTEGER AUTO_INCREMENT,
    evento_id INTEGER  NOT NULL,
    socio_id INTEGER  NOT NULL,
    puntuacion INTEGER,
    comentario VARCHAR(500),
    fecha_creacion DATE,
    PRIMARY KEY(id)
);
